// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCViLF12QBh6oRabhrwygIorYM4ukaLkuE',
    appId: '1:357749336399:web:be4d4ee94771716812bd3a',
    messagingSenderId: '357749336399',
    projectId: 'testing-cli-a9f78',
    authDomain: 'testing-cli-a9f78.firebaseapp.com',
    storageBucket: 'testing-cli-a9f78.appspot.com',
    measurementId: 'G-VDKRDXYX92',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCP2dDRl2rMVMlBge9Pos3_wOfzyNSiAjA',
    appId: '1:357749336399:android:78859d5788422a3f12bd3a',
    messagingSenderId: '357749336399',
    projectId: 'testing-cli-a9f78',
    storageBucket: 'testing-cli-a9f78.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB4Puq2j4lZtNvabLmdQKEhTVKV34hLNEU',
    appId: '1:357749336399:ios:98471c09ab310dd612bd3a',
    messagingSenderId: '357749336399',
    projectId: 'testing-cli-a9f78',
    storageBucket: 'testing-cli-a9f78.appspot.com',
    iosBundleId: 'com.anfal.firebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB4Puq2j4lZtNvabLmdQKEhTVKV34hLNEU',
    appId: '1:357749336399:ios:98471c09ab310dd612bd3a',
    messagingSenderId: '357749336399',
    projectId: 'testing-cli-a9f78',
    storageBucket: 'testing-cli-a9f78.appspot.com',
    iosBundleId: 'com.anfal.firebase',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCViLF12QBh6oRabhrwygIorYM4ukaLkuE',
    appId: '1:357749336399:web:4878b6d30310188e12bd3a',
    messagingSenderId: '357749336399',
    projectId: 'testing-cli-a9f78',
    authDomain: 'testing-cli-a9f78.firebaseapp.com',
    storageBucket: 'testing-cli-a9f78.appspot.com',
    measurementId: 'G-T92NVTQ67Q',
  );
}
